services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        workspace: ../..
        helpers: ../helpers
    ports:
      - "9323:9323"
    volumes:
      - ./test-results:/app/packages/gl/test-results
      - ./tests/__screenshots__:/app/packages/gl/tests/__screenshots__
